import Link from "next/link";

const sections = [
  {
    title: "1. Eligibility and Account Responsibilities",
    body: [
      "Use of the Service is permitted only to individuals and entities capable of entering into legally binding contracts under applicable law. By creating an account, you represent that all information you provide is accurate, complete, and current.",
      "You are solely responsible for maintaining the confidentiality of your login credentials and for all activities conducted under your account. If you suspect unauthorized access, you must notify us promptly. We reserve the right to suspend or terminate any account containing false, misleading, or incomplete information.",
    ],
  },
  {
    title: "2. Description of the Service",
    body: [
      "The Service provides AI-assisted software tools designed to help users identify, evaluate, analyze, and organize business prospecting opportunities. The Service may generate rankings, summaries, recommendations, drafts, diagnostic outputs, and other forms of automated or semi-automated content.",
      "These outputs are intended solely as decision-support tools. You remain exclusively responsible for reviewing, verifying, and determining how to use any information or output generated by the Service.",
    ],
  },
  {
    title: "3. No Professional Advice",
    body: [
      "The Service does not provide legal, financial, accounting, tax, investment, compliance, employment, or other professional advice. Nothing generated by the Service should be interpreted as a guarantee of business outcomes, lead quality, conversion rates, revenue, regulatory compliance, or suitability for any particular purpose.",
      "All outputs may contain inaccuracies, omissions, outdated information, or incorrect inferences. You must independently verify all material information before relying on it or taking action.",
    ],
  },
  {
    title: "4. Acceptable Use",
    body: [
      "Your use of the Service must comply with all applicable laws and these Terms. You may not use the Service in any manner that is unlawful, harmful, fraudulent, deceptive, abusive, defamatory, or otherwise objectionable.",
      "You may not interfere with the operation of the Service, attempt to gain unauthorized access, circumvent security measures, or engage in any activity that could damage, disable, or impair the Service or its infrastructure. Reverse engineering, decompiling, or attempting to extract source code is prohibited except where expressly permitted by law.",
    ],
  },
  {
    title: "5. Your Data and Inputs",
    body: [
      "You are solely responsible for all data, prompts, files, URLs, contact information, and other materials you submit to the Service (\"Inputs\"). By providing Inputs, you represent that you have all necessary rights, permissions, and lawful bases to submit such material and to authorize us to process it in connection with the Service.",
      "You must not upload or submit content that is unlawful, infringing, defamatory, malicious, or that contains sensitive personal information unless the Service expressly supports such use and you have a lawful basis to process that information.",
    ],
  },
  {
    title: "6. Website Access, Crawling, and Public Data",
    body: [
      "The Service may analyze publicly available business information, including website content, metadata, and other publicly accessible online sources, for the purpose of generating insights, rankings, or prospecting intelligence.",
      "The Service does not access password-protected pages, gated portals, private databases, paywalled content, or any material requiring authentication, circumvention of technical restrictions, or unauthorized access.",
      "The Service does not bypass robots.txt directives, rate limits, or standard mechanisms used to manage automated access. Any automated retrieval performed by the Service is limited to publicly accessible information and is conducted in a manner intended to avoid burdening or disrupting third-party websites.",
      "The Service does not collect, process, or analyze patient data, medical records, or other regulated information. You are solely responsible for ensuring that any website, URL, or data you request us to analyze may be lawfully accessed, used, and processed for your intended purpose.",
      "We make no representation regarding the accuracy, completeness, legality, or reliability of any third-party website or publicly available data.",
    ],
  },
  {
    title: "7. Use of Outputs",
    body: [
      "Subject to your compliance with these Terms, you may use outputs generated by the Service for your internal business purposes. Because outputs may be derived from automated systems, public data, and third-party sources, we do not represent or warrant that any output is unique, accurate, complete, or non-infringing.",
      "You bear full responsibility for evaluating and determining how to use any output, including in connection with outreach, marketing, targeting, scoring, or business decision-making.",
    ],
  },
  {
    title: "8. Third-Party Services and Data Sources",
    body: [
      "The Service may rely on or integrate with third-party providers, data sources, hosting services, AI model providers, analytics tools, and external websites. We do not control and are not responsible for third-party content, outages, inaccuracies, or failures.",
      "Your use of third-party services may be subject to separate terms and policies established by those providers. We disclaim all liability arising from your use of or reliance on any third-party service or data source.",
    ],
  },
  {
    title: "9. Fees, Billing, and Subscription Terms",
    body: [
      "Certain features of the Service may require payment of subscription fees or usage-based charges. By purchasing a paid plan, you authorize us and our payment processors to charge all applicable fees, taxes, and other amounts due.",
      "Unless otherwise stated, subscriptions renew automatically until canceled. We may modify pricing, plan features, usage limits, or billing structures prospectively upon reasonable notice.",
    ],
  },
  {
    title: "10. Intellectual Property",
    body: [
      "All software, designs, text, graphics, interfaces, workflows, trademarks, and underlying technology associated with the Service are owned by us or our licensors and are protected by intellectual property laws.",
      "Except for the limited rights expressly granted to you under these Terms, no rights are granted by implication, estoppel, or otherwise. You may not copy, modify, distribute, sell, or create derivative works based on the Service or its content.",
    ],
  },
  {
    title: "11. Suspension and Termination",
    body: [
      "We may suspend, restrict, or terminate your access to the Service at any time, with or without notice, if we believe you have violated these Terms, created risk or liability for us or others, failed to pay amounts due, or used the Service in an abusive, unlawful, or harmful manner.",
      "We may modify or discontinue the Service, in whole or in part, at any time. We are not liable for any suspension, modification, discontinuation, or termination of the Service.",
    ],
  },
  {
    title: "12. Disclaimers",
    body: [
      "The Service is provided on an \"as is\" and \"as available\" basis. To the fullest extent permitted by law, we disclaim all warranties, whether express, implied, statutory, or otherwise, including any implied warranties of merchantability, fitness for a particular purpose, title, non-infringement, accuracy, quiet enjoyment, or results.",
      "We do not warrant that the Service will be uninterrupted, secure, error-free, timely, or free from harmful components, or that defects will be corrected.",
    ],
  },
  {
    title: "13. Limitation of Liability",
    body: [
      "To the maximum extent permitted by California law, we and our affiliates, officers, employees, contractors, licensors, and service providers shall not be liable for any indirect, incidental, special, consequential, exemplary, or punitive damages, or for any loss of profits, revenue, data, goodwill, business opportunity, or other intangible losses arising out of or relating to your use of or inability to use the Service.",
      "To the maximum extent permitted by law, our total aggregate liability for all claims arising out of or relating to the Service or these Terms shall not exceed the greater of one hundred U.S. dollars ($100) or the amount you paid to us for the Service in the twelve months preceding the event giving rise to the claim.",
    ],
  },
  {
    title: "14. Indemnification",
    body: [
      "You agree to defend, indemnify, and hold harmless the Company and its affiliates, officers, employees, contractors, licensors, and service providers from and against any claims, liabilities, damages, losses, judgments, costs, and expenses, including reasonable attorneys' fees, arising out of or related to your use of the Service, your Inputs, your Outputs, your violation of these Terms, or your violation of any law or third-party rights.",
    ],
  },
  {
    title: "15. Governing Law and Dispute Resolution",
    body: [
      "These Terms are governed by the laws of the State of California, without regard to conflict-of-law principles. Any dispute arising out of or relating to these Terms or the Service shall be brought exclusively in the state or federal courts located in California, and you consent to the personal jurisdiction of those courts.",
    ],
  },
  {
    title: "16. Changes to These Terms",
    body: [
      "We may update these Terms from time to time. If we make material changes, we may provide notice through the Service or by other reasonable means. Your continued use of the Service after updated Terms become effective constitutes your acceptance of the revised Terms.",
    ],
  },
  {
    title: "17. Contact Information",
    body: [
      "Questions regarding these Terms may be directed to: support@tryneyma.com",
    ],
  },
];

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-4xl px-6 py-16">
      <div className="rounded-[24px] border border-[var(--border)] bg-[var(--card)] p-6 shadow-[var(--shadow-card)] sm:p-8">
        <p className="section-kicker">Legal</p>
        <h1 className="mt-3 text-3xl font-medium tracking-[-0.04em] text-[var(--text-primary)]">
          Terms of Service
        </h1>
        <p className="mt-3 text-xs uppercase tracking-[0.14em] text-[var(--text-secondary)]">
          Effective Date: March 22, 2026
        </p>
        <p className="mt-5 text-sm leading-7 text-[var(--text-secondary)]">
          These Terms of Service (&ldquo;Terms&rdquo;) constitute a binding agreement between you and Neyma
          (&ldquo;the Company,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;). They govern your access to and use of our website,
          applications, AI-powered prospecting tools, and all related services (collectively, the &ldquo;Service&rdquo;).
        </p>
        <p className="mt-3 text-sm leading-7 text-[var(--text-secondary)]">
          By accessing or using the Service, you acknowledge that you have read, understood, and agree to be bound by
          these Terms. If you do not agree, you must discontinue use of the Service immediately.
        </p>

        <div className="mt-8 space-y-8">
          {sections.map((section) => (
            <section key={section.title}>
              <h2 className="text-lg font-medium tracking-[-0.02em] text-[var(--text-primary)]">
                {section.title}
              </h2>
              <div className="mt-3 space-y-3">
                {section.body.map((paragraph) => (
                  <p key={paragraph} className="text-sm leading-7 text-[var(--text-secondary)]">
                    {paragraph}
                  </p>
                ))}
              </div>
            </section>
          ))}
        </div>

        <div className="mt-10 flex flex-wrap gap-4">
          <Link href="/privacy" className="text-sm font-medium text-[var(--primary)] hover:underline">
            Privacy Policy
          </Link>
          <Link href="/register" className="text-sm font-medium text-[var(--primary)] hover:underline">
            Back to sign up
          </Link>
        </div>
      </div>
    </main>
  );
}
